name: Mirror to Bitbucket Repo
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:MetaCubeX/meta-rules-dat.git
          destination-repo: git@gitee.com:LoogCP/ruleset.git
